config/routes.rb
Rails.application.routes.draw do
  # root 'pages#home'
  root 'sessions#new'
  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create', as: 'log_in'
  delete 'logout', to: 'sessions#destroy'
  get 'password', to: 'passwords#edit', as: 'edit_password'
  patch 'password', to: 'passwords#update'
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { minimum: 5, maximum: 100 }
              validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  # makes Current.user accessible in view files.
  attribute :user
end

app/models/demo.rb
class Demo < ApplicationRecord
  validates :title, presence: true, length: { minimum: 5, maximum: 100 }
  validates :description, presence: true, length: { minimum:10, maximum: 300}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :article
  # adds virtual attributes for authentication
  has_secure_password
  # validates email
  validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: 'Invalid email' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user
  around_action :switch_locale
  def set_current_user
    # finds user with session data and stores it if present
    Current.user = User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def require_user_logged_in!
    # allows only logged in user
    redirect_to sign_in_path, alert: 'You must be signed in' if Current.user.nil?
  end

  def switch_locale(&action)
    lang = params[:lang] || I18n.default_locale
    I18n.with_locale(lang, &action)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :correct_user, only: %i[destroy edit]

  def show
    @article = Article.find(params[:id])
  end

  def index
    if Current.user
      @articles = Article.all
      flash[:notice] = "Welcome #{Current.user.email}" if (Time.now - Current.user.created_at) <= 24 * 60 * 60
    else
      redirect_to root_path
    end
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  def correct_user
    @article = Article.find(params[:id])
    unless Current.user.id == @article.user_id
      redirect_to articles_path, notice: 'Not authorized to do this action'
    end
  end

  private

  def article_params
    params.require(:article).permit(:title, :description, :user_id)
  end
end

app/controllers/demos_controller.rb
class DemosController < ApplicationController
  def shows

  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

  end
  def about
    
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  # allows only logged in users
  before_action :require_user_logged_in!
  def edit; end

  def update
    # update user password
    if Current.user.update(password_params)
      redirect_to root_path, notice: 'Password Updated'
    else
      render :edit
    end
  end

  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    if Current.user
      redirect_to articles_path
    else
      @user = User.new
    end

  end
  def create
    @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        redirect_to root_path, notice: 'Successfully created account'
      else
        render :new
      end
  end
  private

  def user_params
    # strong parameters
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
      if Current.user
        redirect_to articles_path
      end
    end
    def create
      user = User.find_by(email: params[:email])
      # finds existing user, checks to see if user can be authenticated
      if user.present? && user.authenticate(params[:password])
      # sets up user.id sessions
        session[:user_id] = user.id
        redirect_to articles_path
      else
        flash.now[:alert] = 'Invalid email or password'
        render :new
      end
    end
    def destroy
      # deletes user session
      session[:user_id] = nil
      redirect_to root_path, notice: 'Logged Out'
    end
  end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if Current.user
      redirect_to articles_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/edit.html.erb
<div style="padding: 35px; display: flex; justify-content: center;">
    <div style="display: flex; flex-direction:column">
      <h1>Edit Article</h1>
      <div>
          <% if @article.errors.any? %>
              <p style="color: red;">There are errors:</p>
              <ul>
                  <% @article.errors.full_messages.each do |message| %>
                      <li style="color: red;"><%= message %></li>
                  <% end %>
              </ul>
              <% end %>
      </div>
      <div style="border: 2px solid black;padding: 20px">
        <%= form_with model: @article ,local: true, data: { turbo: 'false' } do |form|  %>
          <p>
            <%= form.label :title %> <br/>
            <%= form.text_field :title %>
            <% if @article.errors.has_key?(:title) %>
              <p style="color: red;">Title <%= @article.errors[:title].first %></p>
            <% end %>
          </p>
          <p>
            <%= form.label :description %> <br/>
            <%= form.text_area :description %>
            <% if @article.errors.has_key?(:description) %>
              <p style="color: red;">Description <%= @article.errors[:description].first %></p>
            <% end %>
          </p>
          <p>
            <%= form.submit %>
          </p>
        <% end %>
      </div>
    </div>
  </div>

app/views/articles/index.html.erb
<div style="padding: 35px; display: flex; justify-content: center;">
  <div style="width: 100%; max-width: 800px;">
    <div style="display: flex; flex-direction: row; justify-content: space-between; align-items: center; gap: 10px;">
      <h1 style="text-align: center; color: #333;"><%= t(".articles_listing_page") %></h1>
      <%= button_to t(".create_new_article"), new_article_path, method: :get, style: 'padding: 10px 15px; background-color: #4CAF50; color: white; border: none; cursor: pointer;' %>
      <%= button_to t(".edit_password"), edit_password_path, method: :get, style: 'padding: 10px 15px; background-color: #FF9800; color: white; border: none; cursor: pointer;' %>
      <%= button_to t(".logout"), logout_path, method: :delete, style: 'padding: 10px 15px; background-color: #F44336; color: white; border: none; cursor: pointer;' %>
    </div>
    <div>
      <table style="width: 100%; table-layout: fixed;">
        <thead>
          <tr>
            <th style="text-align: center; padding: 15px;"><%= t(".title") %></th>
            <th style="text-align: center; padding: 15px;"><%= t(".description") %></th>
            <th style="text-align: center; padding: 15px;"><%= t(".author_email_id") %></th>
            <th style="text-align: center; padding: 15px;" colspan="2"><%= t(".action") %></th>
          </tr>
        </thead>
        <tbody>
          <% @articles.each do |article| %>
            <tr>
              <td style="text-align: center; padding: 15px;"><%= article.title %></td>
              <td style="text-align: center; padding: 15px;"><%= article.description %></td>
              <td style="text-align: center; padding: 15px;"><%= User.find_by(id: article.user_id).email %></td>
              <td><%= button_to t(".show"), article_path(article), method: :get, style: 'padding: 5px 10px; background-color: #2196F3; color: white; border: none; cursor: pointer;' %></td>
              <% if Current.user && article.user_id == Current.user.id %>
                <td><%= button_to t(".edit"), edit_article_path(article), method: :get, style: 'padding: 5px 10px; background-color: #FFC107; color: white; border: none; cursor: pointer;' %></td>
                <td><%= button_to t(".delete"), article_path(article), method: :delete, data: { turbo_method: :delete, turbo_confirm: t(".are_you_sure") }, style: 'padding: 5px 10px; background-color: #F44336; color: white; border: none; cursor: pointer;' %></td>
              <% else %>
                <td colspan="2" style="text-align: left; padding: 15px;"><%= t(".not_authorized_for_edit_or_delete") %></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/articles/new.html.erb
<div style="padding: 35px; display: flex; justify-content: center;">
  <div style="display: flex; flex-direction: column; max-width: 600px; width: 100%;">

    <h1 style="text-align: center; color: #333;">Create a New Article</h1>

    <div>
      <% if @article.errors.any? %>
        <p style="color: red; margin-bottom: 10px;">There are errors:</p>
        <ul style="color: red; margin-bottom: 10px;">
          <% @article.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
    </div>

    <div style="border: 2px solid black; padding: 20px; background-color: #f5f5f5;width: 100%">
      <%= form_with scope: :article, url: articles_path, local: true, data: { turbo: 'false' } do |form|  %>
        <p>
          <%= form.label :title, style: 'margin-bottom: 5px; font-weight: bold;' %> <br/>
          <%= form.text_field :title, style: 'padding: 5px; width: 98%;' %>
          <% if @article.errors.has_key?(:title) %>
            <p style="color: red; margin: 5px 0 0 0;"><%= @article.errors[:title].first %></p>
          <% end %>
        </p>
        <p>
          <%= form.label :description, style: 'margin-bottom: 5px; font-weight: bold;' %> <br/>
          <%= form.text_area :description, style: 'padding: 5px; width: 98%; height: 100px;' %>
          <% if @article.errors.has_key?(:description) %>
            <p style="color: red; margin: 5px 0 0 0;"><%= @article.errors[:description].first %></p>
          <% end %>
        </p>
        <p style="visibility: hidden;">
          <%= form.number_field :user_id , value:Current.user.id%>
        </p>
        <p>
          <%= form.submit 'Create', style: 'padding: 10px 15px; background-color: #4CAF50; color: white; border: none; cursor: pointer;' %>
        </p>
      <% end %>
    </div>

  </div>
</div>

app/views/articles/show.html.erb
<div style="padding: 35px;width: 100%;">
    <h1>Show Article</h1>
    <p style="font-size: 15px;"><strong>Title: </strong> <%= @article.title %> </>
    <p style="font-size: 15px;"><strong>Description: </strong> <%= @article.description %> </p>

    <div style="display: flex;flex-direction:row;gap: 20px">
        <%= button_to "Back to article", articles_path, method: :get%>
        <%= button_to 'Edit', edit_article_path(@article), method: :get %>
        <%= button_to 'Delete', article_path(@article), method: :delete, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
    </div>
</div>

app/views/demos/show.html.erb
<h1>Shows Demo</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RorpostgreTraining</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Page</h1>

app/views/pages/home.html.erb
<h1>Hello Guys</h1>

app/views/welcome/index.html.erb
<h1>Rails Authentication</h1>
<%= link_to 'Sign Up', sign_up_path %>
or
<%= link_to 'Login', sign_in_path %>